defaults:
  game: maze
  device: cpu
  env:
    MAZE_OBS_MODE: "pos+rays"
    MAZE_SENSOR_RANGE: 6
    MAZE_SLOW_PENALTY: 5.0
    MAZE_SPEED_BONUS: 10.0
    MAZE_SPEED_POWER: 1.5
    MAZE_NOVELTY_BONUS: 0.002
    MAZE_BACKTRACK_PENALTY: -0.3
    MAZE_FAIL_PENALTY: 50.0
train_timesteps: 750000
n_steps: 512
batch_size: 512
n_epochs: 4
n_envs: 12
iterations_per_set: 4
num_threads: 2
eval_episodes: 16
video_steps: 600
max_video_seconds: 30
profiles:
  quick:
    train_timesteps: 10000
    iterations_per_set: 3
    max_cycles: 1
    eval_episodes: 1
    video_steps: 300
    max_video_seconds: 20
    checkpoint_interval: 0
    no_checkpoint: true
  gpu:
    device: cuda
    batch_size: 1024
    n_envs: 16
    train_timesteps: 500000
