defaults:
  game: pong
  model_prefix: ppo_pong_custom
  train_timesteps: 300000
  n_envs: 8
  eval_episodes: 3
profiles:
  quick:
    train_timesteps: 10000
    iterations_per_set: 1
    max_cycles: 1
    eval_episodes: 1
    video_steps: 300
    max_video_seconds: 20
    checkpoint_interval: 0
    no_checkpoint: true
